version: '3'

services:
  database-services:
    build:
      context: ./database-service
      dockerfile: ./database-service.Dockerfile
      args:
        - APP_PORT=${APP_PORT}
    ports:
      - ${APP_PORT}:${APP_PORT}
    env_file:
      - .env

  mysql:
    image: mysql:8.0
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: email_messaging_app

volumes:
  mysql-data: