swagger: "2.0"
info:
  title: Email Service
  description: "Email service for surya digital teknologi coding test"
  version: 1.0.0
  contact:
    email: "mramdanf@gmail.com"
basePath: localhost:3001
tags:
  - name: Send Email
    description: Send email endpoint
schemes:
  - http
paths:
  /send-email:
    post:
      tags:
        - Send Email
      summary: Send an email to an email address with a specific message.
      x-swagger-router-controller: emailController
      description: ""
      operationId: sendMail
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          required: true
          schema:
            properties:
              email:
                type: string
                example: test@gmail.com
              message:
                type: string
                example: Hey, mohamad ramdan firdaus it's your birthday.
      responses:
        "200":
          description: Email sent successfull
          schema:
            properties:
              status:
                type: string
                example: sent
              sentTiem:
                type: string
                example: "2022-07-01T14:48:00.000Z"
        "400":
          description: Invalid input
        "500":
          description: Server error. 10% of the time this status will be returned.
        "Timeout":
          description: Request timed out. 10% of the time the server will hang.