const MESSAGE_TYPES = {
  BIRTH_DAY: 'birth-day'
};

const SENT_MESSAGE_STATUS = {
  ERROR: 'error',
  SUCCESS: 'success'
};

const CRON_STATUS_TYPE = {
  SEND_BIRTHDAY: 'SEND_BIRTHDAY',
  RESEND_BIRTHDAY: 'RESEND_BIRTHDAY'
};

module.exports = {
  MESSAGE_TYPES,
  SENT_MESSAGE_STATUS,
  CRON_STATUS_TYPE
};
