swagger: "2.0"
info:
  description: "Email Messaging App"
  version: 1.0.0
  title: Email Messaging App Service
  contact:
    email: "mramdanf@gmail.com"
basePath: localhost:3000
tags:
  - name: User
    description: User management endpoints
paths:
  /users:
    post:
      tags:
        - User
      x-swagger-router-controller: userController
      description: ""
      operationId: createUser
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: User object that hold user info detail
          required: true
          schema:
            $ref: "#/definitions/CreateUser"
      responses:
        "400":
          description: Invalid body parameter
        "500":
          description: Internal server error, i.e database operation error
    delete:
      tags:
        - User
      x-swagger-router-controller: userController
      description: ""
      operationId: deleteUser
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Object that hold userId param
          required: true
          schema:
            properties:
              userId:
                type: string
      responses:
        "400":
          description: Invalid userId supplied in delete body
        "404":
          description: User not found or no affected rows database operation result
        "500":
          description: Internal server error, i.e database operation error
    put:
      tags:
        - User
      x-swagger-router-controller: userController
      description: ""
      operationId: updateUser
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: User object to be updated plus userId
          required: true
          schema:
            $ref: "#/definitions/UpdateUser"
      responses:
        "400":
          description: Invalid body parameter
        "404":
          description: User not found or no affected rows database operation result
        "500":
          description: Internal server error, i.e database operation error
definitions:
  CreateUser:
    properties:
      firstName:
        type: string
      lastName:
        type: string
      email:
        type: string
      location:
        type: string
        description: Time zone identifier i.e Asia/Jakarta
  UpdateUser:
    properties:
      userId:
        type: number
      firstName:
        type: string
      lastName:
        type: string
      email:
        type: string
      location:
        type: string
        description: Time zone identifier i.e Asia/Jakarta